Repository KDT3-final-project-team2/frontend, pull requests merged in 2023-03, with the labels that each got.

#3 #2 라우터, 레이아웃 설정
  README.md
  package-lock.json
  package.json
  src/@types/data.d.ts
  src/@types/props.d.ts
  src/App.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/Nav.tsx
  src/components/layouts/Sidebar.tsx
  src/components/layouts/index.tsx
  src/index.css
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/reset.css
Labels: good first issue, 공통 컴포넌트

#8 Feat: global-style추가 및 폰트 적용 / utils 폴더 추가
  package-lock.json
  package.json
  src/App.tsx
  src/assets/fonts/LINESeedKR-Bd.eot
  src/assets/fonts/LINESeedKR-Bd.ttf
  src/assets/fonts/LINESeedKR-Bd.woff
  src/assets/fonts/LINESeedKR-Bd.woff2
  src/assets/fonts/LINESeedKR-Rg.eot
  src/assets/fonts/LINESeedKR-Rg.ttf
  src/assets/fonts/LINESeedKR-Rg.woff
  src/assets/fonts/LINESeedKR-Rg.woff2
  src/assets/fonts/LINESeedKR-Th.eot
  src/assets/fonts/LINESeedKR-Th.ttf
  src/assets/fonts/LINESeedKR-Th.woff
  src/assets/fonts/LINESeedKR-Th.woff2
  src/style/font.css
  src/style/globalStyle.ts
  src/utils/cookie.ts
Labels: Feat, 공통 컴포넌트

#10 Feat : 기업고객 회원가입, 유효성검사 완료
  index.html
  package-lock.json
  package.json
  src/@types/data.d.ts
  src/@types/props.d.ts
  src/App.tsx
  src/components/SearchAddress.tsx
  src/pages/CompanySignup.tsx
  src/reset.css
  tsconfig.json
Labels: Feat, 기업고객

#12 Fix : 기업고객 주소입력 후 에러메세지 제거
  src/components/SearchAddress.tsx
  src/pages/CompanySignup.tsx
  src/utils/validationSchema.ts
Labels: 기업고객, Fix

#13 Feat : 비밀번호 확인 input 추가
  src/@types/data.d.ts
  src/pages/ApplicantSignUp.tsx
  src/utils/validationSchema.ts
Labels: Feat, 지원자

#14 Feature/#5
  package-lock.json
  package.json
  src/@types/data.d.ts
  src/components/common/AlertModal.tsx
  src/components/common/ConfirmModal.tsx
  src/pages/Login.tsx
  src/style/globalStyle.ts
  src/utils/validationSchema.ts
Labels: Feat, 공통 컴포넌트

#17 Feat : 임시 홈, 대시보드 라우트, 레이아웃 설정
  package-lock.json
  src/App.css
  src/App.tsx
  src/components/common/AlertModal.tsx
  src/components/common/ConfirmModal.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/LeftBar.tsx
  src/components/layouts/Nav.tsx
  src/components/layouts/RightBar.tsx
  src/components/layouts/Sidebar.tsx
  src/components/layouts/index.tsx
  src/index.css
  src/pages/AdminMain.tsx
  src/pages/ApplicantMain.tsx
  src/pages/CompanyMain.tsx
  src/pages/CompanySignup.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/reset.css
  src/style/globalStyle.ts
Labels: Feat, 공통 컴포넌트

#19 Feat : 로그인, 회원가입 레이아웃 설정
  src/App.tsx
  src/components/layouts/RightBar.tsx
  src/components/layouts/index.tsx
  src/pages/Home.tsx
  src/style/globalStyle.ts
Labels: Feat, 공통 컴포넌트

#20 Feat: 리덕스 툴킷 / 로딩 추가
  index.html
  package-lock.json
  package.json
  src/@types/data.d.ts
  src/App.css
  src/App.tsx
  src/assets/logo.svg
  src/assets/react.svg
  src/components/common/AlertModal.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/Loading.tsx
  src/hooks/useDispatchHooks.ts
  src/lotties/loading.json
  src/main.tsx
  src/pages/Login.tsx
  src/store/loadingSlice.ts
  src/store/store.ts
  src/store/userSlice.ts
Labels: Feat, 공통 컴포넌트

#22 Feat : 왼쪽네브바 내용 추가
  src/App.tsx
  src/assets/icons/applicant.png
  src/assets/icons/contract.png
  src/assets/icons/home.png
  src/assets/icons/jobposting.png
  src/components/layouts/LeftBar.tsx
  src/components/layouts/index.tsx
  src/constants/navigation.ts
  src/pages/Home.tsx
  src/pages/applicant/ApplicantJobSearching.tsx
  src/pages/applicant/ApplicantMain.tsx
  src/pages/applicant/ApplicantMyInfo.tsx
  src/pages/applicant/ApplicantResume.tsx
  src/pages/company/CompanyApplicant.tsx
  src/pages/company/CompanyContract.tsx
  src/pages/company/CompanyJobPosting.tsx
  src/pages/company/CompanyMain.tsx
  src/style/globalStyle.ts
Labels: Feat, 공통 컴포넌트

#23 Feature/#21
  src/@types/props.d.ts
  src/components/layouts/index.tsx
  src/components/signup/ApplicantSignUpForm.tsx
  src/components/signup/CompanySignUpForm.tsx
  src/components/signup/SignUpPaginationButton.tsx
  src/components/signup/SignUpStepCheck.tsx
  src/components/signup/SignUpTitle.tsx
  src/components/signup/Step1.tsx
  src/components/signup/Step2.tsx
  src/components/signup/Step3.tsx
  src/components/signup/Step4.tsx
  src/pages/ApplicantSignUp.tsx
  src/pages/CompanySignup.tsx
Labels: Feat, 기업고객, 지원자, 공통 컴포넌트

#25 Feature/#5
  index.html
  src/@types/data.d.ts
  src/assets/favicon.svg
  src/assets/google.svg
  src/assets/kakao.svg
  src/assets/loginContent.png
  src/assets/logo.svg
  src/components/layouts/RightBar.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/style/globalStyle.ts
Labels: Feat, 기업고객, 지원자

#29 Feat: 관리자 경로 및 로그인 추가
  src/App.css
  src/App.tsx
  src/assets/icons/setting.png
  src/components/layouts/LeftBar.tsx
  src/components/layouts/RightBar.tsx
  src/components/layouts/index.tsx
  src/constants/navigation.ts
  src/index.css
  src/main.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/admin/AdminLogin.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/admin/AdminMember.tsx
  src/pages/admin/AdminSetting.tsx
  src/pages/admin/AdminTerm.tsx
Labels: Feat, 어드민

#31 Design : 회원가입 화면 디자인 , 폼 수정
  src/@types/data.d.ts
  src/@types/props.d.ts
  src/assets/icons/check.png
  src/assets/icons/toggleArrowDown.png
  src/assets/icons/toggleArrowUp.png
  src/assets/images/welcome.png
  src/components/common/DropDown.tsx
  src/components/layouts/LeftBar.tsx
  src/components/signup/ApplicantSignUpForm.tsx
  src/components/signup/CheckBox.tsx
  src/components/signup/CompanySignUpForm.tsx
  src/components/signup/SignUpPaginationButton.tsx
  src/components/signup/SignUpStepCheck.tsx
  src/components/signup/SignUpTitle.tsx
  src/components/signup/Step1.tsx
  src/components/signup/Step2.tsx
  src/components/signup/Step3.tsx
  src/components/signup/Step4.tsx
  src/constants/signupSteps.ts
  src/constants/terms.ts
  src/pages/ApplicantSignUp.tsx
  src/pages/CompanySignUp.tsx
  src/pages/Home.tsx
  src/style/globalStyle.ts
  src/utils/validationSchema.ts
Labels: Feat, 기업고객, 지원자

#34 Feat: 채용공고 미리보기 모달창
  src/@types/props.d.ts
  src/assets/icons/pdfFile.png
  src/components/companyjobposting/JobPostingList.tsx
  src/components/companyjobposting/Modal.tsx
  src/components/companyjobposting/ModalWindow.tsx
  src/components/companyjobposting/PostEditModal.tsx
  src/components/companyjobposting/PreviewModal.tsx
  src/pages/company/CompanyJobPosting.tsx
Labels: Feat, 기업고객

#37 Design : 병원 메인홈 디자인, 이메일전송 모달 생성
  package-lock.json
  package.json
  src/@types/props.d.ts
  src/App.tsx
  src/assets/icons/email.png
  src/components/common/WebEditor.tsx
  src/components/layouts/RightBar.tsx
  src/components/mainhome/EmailModal.tsx
  src/components/mainhome/List.tsx
  src/components/mainhome/StepBox.tsx
  src/components/signup/ApplicantSignUpForm.tsx
  src/components/signup/SignUpStepCheck.tsx
  src/constants/navigation.ts
  src/constants/signupSteps.ts
  src/constants/steps.ts
  src/pages/Home.tsx
  src/pages/applicant/ApplicantMyInfo.tsx
  src/pages/applicant/ApplicantSetting.tsx
  src/pages/company/CompanyContract.tsx
  src/pages/company/CompanyMain.tsx
  src/pages/company/CompanySetting.tsx
  vite.config.ts
Labels: Feat, 기업고객

#39 Fix : 배포환경 오류 해결
  index.html
  public/_redirects
  public/favicon.svg
  public/google.svg
  public/icons/applicant.png
  public/icons/check.png
  public/icons/close.png
  public/icons/contract.png
  public/icons/email.png
  public/icons/home.png
  public/icons/jobposting.png
  public/icons/jobsearching.png
  public/icons/link.png
  public/icons/member.png
  public/icons/more_vertical.png
  public/icons/pdfFile.png
  public/icons/resume.png
  public/icons/selectfile.png
  public/icons/setting.png
  public/icons/term.png
  public/icons/toggleArrowDown.png
  public/icons/toggleArrowUp.png
  public/images/welcome.png
  public/kakao.svg
  public/loginContent.png
  public/logo.svg
  public/vite.svg
  src/components/common/DropDown.tsx
  src/components/common/WebEditor.tsx
  src/components/companyjobposting/JobPostingList.tsx
  src/components/companyjobposting/PostEditModal.tsx
  src/components/companyjobposting/PreviewModal.tsx
  src/components/layouts/LeftBar.tsx
  src/components/mainhome/EmailModal.tsx
  src/components/mainhome/List.tsx
  src/components/signup/CheckBox.tsx
  src/components/signup/Step1.tsx
  src/components/signup/Step3.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/admin/AdminLogin.tsx
  src/pages/company/CompanyMain.tsx
  src/style/globalStyle.ts
  tsconfig.json
  vite.config.ts
Labels: Fix

#42 Feature/#30
  package-lock.json
  package.json
  public/icons/bookmark.svg
  public/icons/mail.svg
  public/images/loginContent.png
  src/components/common/SelectBox.tsx
  src/components/companyApplicant/ApplicantsInfo.tsx
  src/components/companyApplicant/ApplicantsRecommend.tsx
  src/components/companyApplicant/ApplicantsStats.tsx
  src/components/companyApplicant/MailTemplate.tsx
  src/pages/Home.tsx
  src/pages/admin/AdminLogin.tsx
  src/pages/company/CompanyApplicant.tsx
  src/style/globalStyle.ts
Labels: Feat, 기업고객, 공통 컴포넌트

#43 Feat: 관리자, 기업 회원 약관 관리 페이지 디자인
  package-lock.json
  public/icons/edit.png
  public/icons/trashcan.png
  src/@types/props.d.ts
  src/App.tsx
  src/components/common/WebEditor.tsx
  src/components/companyjobposting/JobPostingList.tsx
  src/components/companyjobposting/PostEditModal.tsx
  src/components/term.tsx/TermList.tsx
  src/components/term.tsx/TermPostEditModal.tsx
  src/constants/navigation.ts
  src/constants/termExample.ts
  src/constants/termsOptions.ts
  src/pages/admin/AdminTerm.tsx
  src/pages/company/CompanyJobPosting.tsx
  src/pages/company/CompanyTerm.tsx
  src/utils/validationSchema.ts
Labels: Feat, 기업고객, 어드민
