Repository KDT3-final-project-team2/frontend, pull requests merged in 2023-04, with the labels that each got.

#50 Feat: 달력 디자인
  package-lock.json
  package.json
  public/icons/add.png
  public/icons/delete.png
  public/icons/dubbleArrow.png
  src/@types/data.d.ts
  src/@types/props.d.ts
  src/components/calendar/CalendarUI.styles.ts
  src/components/calendar/CalendarUI.tsx
  src/components/calendar/ScheduleElement.tsx
  src/components/calendar/UserProfile.tsx
  src/components/layouts/RightBar.tsx
  src/components/layouts/index.tsx
  src/constants/dayOfWeek.ts
  src/pages/Calendar.tsx
  src/pages/Login.tsx
  src/utils/validationSchema.ts
Labels: Feat, 공통 컴포넌트

#53 Feat: 이력서 pdf 미리보기 추가
  package-lock.json
  package.json
  src/@types/data.d.ts
  src/components/applicantResume/ResumeList.tsx
  src/components/applicantResume/ResumeModal.tsx
  src/components/applicantResume/pdf/ViewPDF.tsx
  src/pages/applicant/ApplicantResume.tsx
Labels: Feat, 지원자

#54 Feat: 개인/기업 설정 추가
  public/icons/check.svg
  src/@types/data.d.ts
  src/@types/props.d.ts
  src/components/setting/applicant/Info.tsx
  src/components/setting/applicant/Withdrawal.tsx
  src/components/setting/company/Info.tsx
  src/components/setting/company/PlanPrice.tsx
  src/components/setting/company/Withdrawal.tsx
  src/pages/applicant/ApplicantSetting.tsx
  src/pages/company/CompanyApplicant.tsx
  src/pages/company/CompanySetting.tsx
Labels: Feat, 지원자, 어드민

#57 Feat : 병원 메인홈 목데이터 연결
  public/data/applications.json
  src/@types/data.d.ts
  src/@types/props.d.ts
  src/api/companyApi.ts
  src/components/companyApplicant/ApplicantsList.tsx
  src/components/mainhome/ApplicantList.tsx
  src/components/mainhome/EmailModal.tsx
  src/components/mainhome/StepBox.tsx
  src/constants/mailSample.ts
  src/constants/steps.ts
  src/pages/applicant/ApplicantMain.tsx
  src/pages/company/CompanyMain.tsx
  src/utils/getDday.ts
Labels: Feat, 기업고객

#58 Feat: 슈퍼관리자 약관 관련 기능(api)
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/@types/data.d.ts
  src/@types/props.d.ts
  src/api/adminApi.ts
  src/api/companyApi.ts
  src/components/companyjobposting/PostEditModal.tsx
  src/components/term.tsx/TermList.tsx
  src/components/term.tsx/TermPostEditModal.tsx
  src/constants/termsOptions.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.js
  src/pages/admin/AdminSetting.tsx
  src/pages/admin/AdminTerm.tsx
  src/utils/validationSchema.ts
Labels: Feat, 어드민

#59 Feat: 로그인 로직 추가
  package.json
  src/api/applicantApi.ts
  src/api/commonApi.ts
  src/api/companyApi.ts
  src/api/instance.ts
  src/components/applicantResume/ResumeList.tsx
  src/components/setting/applicant/Info.tsx
  src/components/setting/applicant/Withdrawal.tsx
  src/components/setting/company/Info.tsx
  src/components/setting/company/Withdrawal.tsx
  src/main.tsx
  src/pages/Login.tsx
  src/pages/admin/AdminLogin.tsx
  src/pages/applicant/ApplicantResume.tsx
Labels: Feat, 기업고객, 지원자, 어드민

#62 Feat/#41
  public/data/myApplications.json
  src/@types/data.d.ts
  src/api/applicantApi.ts
  src/api/commonApi.ts
  src/api/companyApi.ts
  src/components/mainhome/ApplicantList.tsx
  src/components/mainhome/EmailModal.tsx
  src/components/mainhome/JobList.tsx
  src/components/mainhome/PlanUserBox.tsx
  src/components/setting/company/Info.tsx
  src/components/signup/ApplicantSignUpForm.tsx
  src/components/signup/CompanySignUpForm.tsx
  src/components/signup/Step1.tsx
  src/constants/mailSample.ts
  src/constants/signupInput.ts
  src/pages/ApplicantSignUp.tsx
  src/pages/CompanySignUp.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/applicant/ApplicantMain.tsx
  src/pages/company/CompanyMain.tsx
  src/utils/validationSchema.ts
Labels: Feat, 기업고객, 지원자

#64 Feat/#63
  src/@types/data.d.ts
  src/api/adminApi.ts
  src/api/instance.ts
  src/components/applicantJobSearching/JobSearchingList.tsx
  src/components/mainhome/NewUsersBox.tsx
  src/components/mainhome/PlanUserBox.tsx
  src/components/mainhome/UserSector.tsx
  src/components/mainhome/UserStaticsBox.tsx
  src/components/member/UserList.tsx
  src/pages/Login.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/admin/AdminMember.tsx
Labels: Feat, 어드민

#65 feat: amaizng-chart / 로그아웃 api 추가
  package-lock.json
  package.json
  public/icons/bookmarkFill.svg
  public/icons/logout.svg
  public/icons/notification.svg
  src/App.tsx
  src/components/companyApplicant/ApplicantsStats.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/index.tsx
  src/main.tsx
  vite.config.ts
Labels: Feat, 공통 컴포넌트

#69 Feat: 슈퍼관리자, 기업회원 약관 관리 api 연결
  package-lock.json
  src/@types/data.d.ts
  src/@types/props.d.ts
  src/api/adminApi.ts
  src/api/companyApi.ts
  src/components/term.tsx/TermList.tsx
  src/components/term.tsx/TermPostEditModal.tsx
  src/constants/termsOptions.ts
  src/hooks/useTermChangeToEnglish.ts
  src/pages/admin/AdminTerm.tsx
  src/pages/company/CompanyJobPosting.tsx
Labels: Feat

#70 Feat: 유저 정보 Slice 생성 / api 추가
  public/icons/volunteer.png
  src/@types/data.d.ts
  src/api/applicantApi.ts
  src/api/companyApi.ts
  src/components/layouts/Header.tsx
  src/constants/navigation.ts
  src/store/applicantUserSlice.ts
  src/store/companyUserSlice.ts
  src/store/store.ts
  src/store/userSlice.ts
Labels: Feat, 기업고객, 지원자

#71 Feat/#68
  package-lock.json
  package.json
  src/@types/data.d.ts
  src/@types/props.d.ts
  src/api/applicantApi.ts
  src/api/commonApi.ts
  src/components/mainhome/JobList.tsx
  src/components/mainhome/StepBox.tsx
  src/components/member/UserList.tsx
  src/components/signup/CheckBox.tsx
  src/components/signup/Step1.tsx
  src/constants/steps.ts
  src/constants/terms.ts
  src/pages/ApplicantSignUp.tsx
  src/pages/CompanySignUp.tsx
  src/pages/applicant/ApplicantMain.tsx
  src/utils/getDday.ts
Labels: Feat, 기업고객, 지원자

#73 Feat: 채용공고, 캘린더 api 연결
  src/@types/data.d.ts
  src/@types/props.d.ts
  src/api/commonApi.ts
  src/api/companyApi.ts
  src/components/calendar/CalendarUI.styles.ts
  src/components/calendar/CalendarUI.tsx
  src/components/calendar/ScheduleElement.tsx
  src/components/calendar/UserProfile.tsx
  src/components/companyjobposting/JobPostingList.tsx
  src/components/companyjobposting/PostEditModal.tsx
  src/components/companyjobposting/PreviewModal.tsx
  src/components/companyjobposting/SelectBox.tsx
  src/hooks/useDateToString.ts
  src/pages/Calendar.tsx
  src/pages/applicant/ApplicantJobSearching.tsx
  src/pages/company/CompanyJobPosting.tsx
  src/utils/optionChangeToEnglish.ts
Labels: Feat

#74 Feat/#68
  src/@types/data.d.ts
  src/@types/props.d.ts
  src/App.tsx
  src/api/applicantApi.ts
  src/api/companyApi.ts
  src/components/common/WebEditor.tsx
  src/components/companyApplicant/ApplicantsList.tsx
  src/components/companyApplicant/MailTemplateModal.tsx
  src/components/companyjobposting/PostEditModal.tsx
  src/components/mainhome/ApplicantList.tsx
  src/components/mainhome/ApplicantStepBox.tsx
  src/components/mainhome/CompanyStepBox.tsx
  src/components/mainhome/EmailModal.tsx
  src/components/mainhome/JobList.tsx
  src/components/signup/CompanySignUpForm.tsx
  src/components/signup/Step3.tsx
  src/constants/mailSample.ts
  src/constants/steps.ts
  src/pages/Login.tsx
  src/pages/applicant/ApplicantMain.tsx
  src/pages/company/CompanyMain.tsx
Labels: Feat, 기업고객

#76 Feat: 공고 검색 api 연결
  src/@types/data.d.ts
  src/@types/props.d.ts
  src/api/applicantApi.ts
  src/components/applicantJobSearching/JobSearchingList.tsx
  src/components/calendar/CalendarUI.tsx
  src/components/companyjobposting/PreviewModal.tsx
  src/components/term.tsx/TermList.tsx
  src/components/term.tsx/TermPostEditModal.tsx
  src/constants/jobPostingOptions.ts
  src/pages/applicant/ApplicantJobSearching.tsx
  src/utils/dateToSTring.ts
  src/utils/termChangeToEnglish.ts
Labels: Feat, 지원자

#77 Feat: 설정 api 연동
  package-lock.json
  package.json
  src/@types/data.d.ts
  src/api/applicantApi.ts
  src/api/companyApi.ts
  src/api/instance.ts
  src/components/applicantResume/ResumeModal.tsx
  src/components/applicantResume/pdf/ViewPDF.tsx
  src/components/common/DropDown.tsx
  src/components/companyApplicant/ApplicantsInfo.tsx
  src/components/layouts/Header.tsx
  src/components/setting/applicant/Info.tsx
  src/components/setting/company/Info.tsx
  src/pages/applicant/ApplicantResume.tsx
  src/pages/applicant/ApplicantSetting.tsx
  src/utils/jwtCheck.ts
  src/utils/validationSchema.ts
Labels: Feat, 기업고객, 지원자

#79 Feat: 지원하기 api, 공고검색 시 모집마감일이 지난 건 filter 처리해주기
  src/api/applicantApi.ts
  src/components/applicantJobSearching/JobSearchingList.tsx
Labels: Feat, 지원자

#80 Feat: pdf 미리보기 사진으로 대체
  src/components/applicantJobSearching/JobSearchingList.tsx
  src/components/companyjobposting/JobPostingList.tsx
  src/components/companyjobposting/PostEditModal.tsx
  src/components/companyjobposting/PreviewModal.tsx
  src/components/term.tsx/TermList.tsx
  src/utils/validationSchema.ts
Labels: Feat

#81 Feat: 지원자 정보 api 연결
  src/api/companyApi.ts
  src/components/companyApplicant/ApplicantsInfo.tsx
  src/components/companyApplicant/ApplicantsList.tsx
  src/components/companyApplicant/ApplicantsRecommend.tsx
Labels: Feat, 기업고객

#82 Feat: 이력서 등록 api 추가
  src/api/applicantApi.ts
  src/components/applicantResume/ResumeModal.tsx
Labels: Feat, 지원자

#84 Feat: 이력서 조회/삭제 api 추가
  src/api/applicantApi.ts
  src/components/applicantResume/ResumeList.tsx
  src/components/applicantResume/ResumeModal.tsx
  src/pages/applicant/ApplicantResume.tsx
Labels: Feat

#85 Feature/#66
  src/components/applicantJobSearching/JobSearchingList.tsx
  src/components/companyjobposting/PreviewModal.tsx
  src/pages/company/CompanyJobPosting.tsx
Labels: Fix

#91 Feat: 병원탐색 페이지 전체공고 조회 기능
  package-lock.json
  package.json
  src/api/applicantApi.ts
  src/api/companyApi.ts
  src/components/applicantJobSearching/JobSearchingList.tsx
  src/hooks/useJobPostsHooks.ts
  src/pages/applicant/ApplicantJobSearching.tsx
Labels: Feat, 지원자

#92 Feat : 메모 작성 디바운싱 처리
  src/components/mainhome/ApplicantList.tsx
  src/pages/company/CompanyJobPosting.tsx
  src/pages/company/CompanyMain.tsx
Labels: enhancement
